name: patrol_flavored_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  patrol: ^3.7.3

flutter:
  uses-material-design: true

patrol:
  app_name: Patrol Flavored App
  flavor: free
  android:
    package_name: com.example.patrol_flavored_app
  ios:
    bundle_id: com.example.patrolFlavoredApp
  macos:
    bundle_id: com.example.macos.patrolFlavoredApp